### ISSUE TITLE
UI Design of the Homepage

### ISSUE THREAD

**Issue by StillAbeginnerr** [TyplibDigitalLibrary/Frontend#2]
### Description
The academic library website requires a modern and intuitive user interface (UI) design for the homepage. The homepage should provide a visually appealing and user-friendly experience, allowing visitors to easily navigate and access the library's resources and services.

### Requirements
1. **Visual Design:**
   - The homepage design should align with the library's branding guidelines, including color scheme, typography, and logo placement.
   - The layout should be clean, organized, and visually appealing, with proper use of whitespace and hierarchy.
   - Relevant imagery, icons, or illustrations should be incorporated to enhance the visual appeal and convey the library's purpose.

**Comment by StillAbeginnerr** [comment]
![image](https://github.com/TyplibDigitalLibrary/Frontend/assets/88205668/0052e749-8b9e-4e7f-b00e-6d05d7121ee4)
@thejediboySHASHANK

**Comment by thejediboySHASHANK** [comment]
LGTM! 

Clean and simple. 
Please visualize the credit based subscription metric to avoid burning our API usage costs or limits.

**Comment by StillAbeginnerr** [comment]
![image](https://github.com/TyplibDigitalLibrary/Frontend/assets/88205668/3a8552fa-6a52-4365-bdd1-368fba598e94)

<b>Added a Credit Button on NavBar.
The Text will be changed to "Purchase" after the Exhaustion of Free Credit Limit.</b>

**Comment by StillAbeginnerr** [comment]
Let's have Black and Green be fixed with our colour palette with a white background on Light-Mode Theme.

**Comment by StillAbeginnerr** [comment]
@thejediboySHASHANK 
Please review the corrected design for further improvements.

**Comment by thejediboySHASHANK** [comment]
LGTM!
