### ISSUE TITLE
Configuring TSX in Reactjs for setting up the codebase.

### ISSUE THREAD

**Issue by StillAbeginnerr** [TyplibDigitalLibrary/Frontend#7]
Configuring TypeScript (TSX) in React.js codebase to streamline the process for development of UI.

**Comment by StillAbeginnerr** [comment]
@thejediboySHASHANK 
Please review the codebase.

**Comment by thejediboySHASHANK** [comment]
LGTM!

Please deploy it on Vercel to visually see changes and modifications.
